### ISSUE TITLE
Socket errors

### ISSUE THREAD

**Issue by xena68** [HcDevel/SiriAPI8#17]
After running for several days, SiriAPI8 stopped working with the following exceptions.  On restart, things are working fine again.  I'll report back if I see this again, but debugging this is way out of my league...

Connection failure
Logout succesful
Trying to reconnect
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 86, in __fetch
    self.connection.noop()
  File "/usr/lib/python3.2/imaplib.py", line 605, in noop
    return self._simple_command('NOOP')
  File "/usr/lib/python3.2/imaplib.py", line 1121, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.2/imaplib.py", line 949, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.2/imaplib.py", line 1064, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.2/imaplib.py", line 977, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.2/imaplib.py", line 1074, in _get_line
    line = self.readline()
  File "/usr/lib/python3.2/imaplib.py", line 265, in readline
    return self.file.readline()
  File "/usr/lib/python3.2/socket.py", line 287, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.2/ssl.py", line 399, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.2/ssl.py", line 293, in read
    v = self._sslobj.read(len, buffer)
socket.error: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 32, in connect
    self.connection = imaplib.IMAP4_SSL("imap.mail.me.com", "993") #Connect to s              erver
  File "/usr/lib/python3.2/imaplib.py", line 1194, in **init**
    IMAP4.**init**(self, host, port)
  File "/usr/lib/python3.2/imaplib.py", line 170, in **init**
    self.open(host, port)
  File "/usr/lib/python3.2/imaplib.py", line 1206, in open
    IMAP4.open(self, host, port)
  File "/usr/lib/python3.2/imaplib.py", line 246, in open
    self.sock = self._create_socket()
  File "/usr/lib/python3.2/imaplib.py", line 1197, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/lib/python3.2/imaplib.py", line 236, in _create_socket
    return socket.create_connection((self.host, self.port))
  File "/usr/lib/python3.2/socket.py", line 397, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 97, in __fetch
    self.connect(False)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 34, in connect
    raise Exception("Connection to iCloud failed. Check your internet connection              ")
Exception: Connection to iCloud failed. Check your internet connection

**Comment by RobinMeis** [comment]
The source exception was raised during the handling of the noop request which is located in the normal IMAP request loop. Any exception in this loop resets the connection and causes a reconnect.
During the reconnect occurred the exception which was displayed and raised by SiriAPI8 and says that there was an error during reconnect.
I can't imagine why this error occurred because I implemented this feature to handle connection outages during the daily IPv4 reconnect. Maybe I didn't handle any exception which might be raised. I will take a closer look into the code when I'm back at my computer.

**Comment by xena68** [comment]
After running fine for several days, I received a similar, but different, exception:

Traceback (most recent call last):
  File "/usr/lib/python3.2/imaplib.py", line 949, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.2/imaplib.py", line 1064, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.2/imaplib.py", line 977, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.2/imaplib.py", line 1076, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 68, in __fetch
    recent = self.connection.recent() #Check for new notes
  File "/usr/lib/python3.2/imaplib.py", line 311, in recent
    typ, dat = self.noop()  # Prod server for response
  File "/usr/lib/python3.2/imaplib.py", line 605, in noop
    return self._simple_command('NOOP')
  File "/usr/lib/python3.2/imaplib.py", line 1121, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.2/imaplib.py", line 951, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: NOOP => socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 37, in connect
    self.connection.login(self.username, self.password) #Login
  File "/usr/lib/python3.2/imaplib.py", line 530, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/usr/lib/python3.2/imaplib.py", line 1121, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.2/imaplib.py", line 957, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: LOGIN command error: BAD [b'[UNAVAILABLE] Service temporarily una                 vailable']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 97, in __fetch
    self.connect(False)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 39, in connect
    raise Exception("Login to iCloud failed. Check user credentials")
Exception: Login to iCloud failed. Check user credentials

**Comment by xena68** [comment]
Not sure if this is the same error, but SiriAPI8 crashed again on me.  I think it was during the 24 hours my internet provider was down.

I do not really understand how python3 exceptions are handled.  Can someone guide me on how I can integrate a call to my prowl class to notify me of exceptions so i can restart SiriAPI8 when it crashes.  I don't need the exact calls, just an example of where I should put the call in the exception handler.

Thanks 

Connection failure
Logout succesful
Trying to reconnect
Traceback (most recent call last):
  File "control4.py", line 517, in <module>
    input("Press any key...\n")
IOError: [Errno 9] Bad file descriptor
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 68, in __fetch
    recent = self.connection.recent() #Check for new notes
  File "/usr/lib/python3.2/imaplib.py", line 311, in recent
    typ, dat = self.noop()  # Prod server for response
  File "/usr/lib/python3.2/imaplib.py", line 605, in noop
    return self._simple_command('NOOP')
  File "/usr/lib/python3.2/imaplib.py", line 1121, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.2/imaplib.py", line 949, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.2/imaplib.py", line 1064, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.2/imaplib.py", line 977, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.2/imaplib.py", line 1074, in _get_line
    line = self.readline()
  File "/usr/lib/python3.2/imaplib.py", line 265, in readline
    return self.file.readline()
  File "/usr/lib/python3.2/socket.py", line 287, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.2/ssl.py", line 399, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.2/ssl.py", line 293, in read
    v = self._sslobj.read(len, buffer)
socket.error: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 32, in connect
    self.connection = imaplib.IMAP4_SSL("imap.mail.me.com", "993") #Connect to server
  File "/usr/lib/python3.2/imaplib.py", line 1194, in **init**
    IMAP4.**init**(self, host, port)
  File "/usr/lib/python3.2/imaplib.py", line 170, in **init**
    self.open(host, port)
  File "/usr/lib/python3.2/imaplib.py", line 1206, in open
    IMAP4.open(self, host, port)
  File "/usr/lib/python3.2/imaplib.py", line 246, in open
    self.sock = self._create_socket()
  File "/usr/lib/python3.2/imaplib.py", line 1197, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/lib/python3.2/imaplib.py", line 236, in _create_socket
    return socket.create_connection((self.host, self.port))
  File "/usr/lib/python3.2/socket.py", line 397, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 97, in __fetch
    self.connect(False)
  File "/home/pi/SiriAPI8/SiriAPI8/SiriAPI.py", line 34, in connect
    raise Exception("Connection to iCloud failed. Check your internet connection")
Exception: Connection to iCloud failed. Check your internet connection

**Comment by RobinMeis** [comment]
I found the problem and solved it. New version will be released soon.
