### ISSUE TITLE
imap error

### ISSUE THREAD

**Issue by jaikumar-b** [HcDevel/SiriAPI8#19]
I am getting this error on running the example.py. Any ideas how to resolve this?

Traceback (most recent call last):
  File "example.py", line 11, in <module>
    SiriAPI.connect() #Connect to iCloud
  File "/Users/jbhambhwani/Documents/SiriAPI8/SiriAPI8/SiriAPI.py", line 43, in connect
    typ, data = self.connection.search(None, 'ALL', 'SUBJECT "' + self.keyword + '"') #Delete unhandled commands with keyword (TODO: deal with alternative execution in future)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imaplib.py", line 660, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imaplib.py", line 1133, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imaplib.py", line 881, in _command
    ', '.join(Commands[name])))
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

**Comment by stofakiller** [comment]
Hi,

I have exact the same problem... I have triede it on windows and linux...

Regards,
Jan

**Comment by kilipet** [comment]
Hi,
same problem here. I have tried on different computers with different phyton-versions (all windows).

Kilian

**Comment by RobinMeis** [comment]
Do you have note sync enabled? I think this happens because the Notes folder can't be selected and then the search raises an exeption

**Comment by stofakiller** [comment]
How to check/disable note sync?

**Comment by RobinMeis** [comment]
Visit iCloud.com and check if you can see your notes after login

**Comment by RobinMeis** [comment]
No response
